baseURL = "https://daily.shuang.blog/"
languageCode = "zh-cn"
title = "小径分岔的兔子洞"
# Pagination setting
# paginate = 10  # Shows 10 items per page (deprecated)
[pagination]
  pagerSize = 10  # Shows 10 items per page

# 主题配置
theme = "paper"

# Paper 主题配置
[params]
  # 颜色主题
  color = "linen"  # linen, wheat, gray, light
  # 头部社交图标
  mastodon = "https://yangyang.how/@shuang"
  threads = "@0b00101111"
  # 首页个人资料
  avatar = "https://daily.shuang.blog/images/avatar.jpg"
  name = "47Fork"
  bio = "Existence precedes essence."
  # 其他设置
  disableHLJS = true       # 禁用 highlight.js
  monoDarkIcon = true      # 显示单色暗模式图标
  # 主要内容区域设置
  mainSections = ["posts", "daily", "xikang"]

# 永久链接 - 影响 URL 结构
[permalinks]
  posts = "/posts/:year/:month/:title/"
  daily = "/daily/:year/:month/:day/"
  xikang = "/xikang/:year/:month/:title/"

# 分类设置
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# 菜单配置
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "博客"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "daily"
    name = "日更"
    url = "/daily/"
    weight = 20
  [[menu.main]]
    identifier = "xikang"
    name = "细糠"
    url = "/xikang/"
    weight = 30
  [[menu.main]]
    identifier = "timeline"
    name = "这些年"
    url = "/这些年/"
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow raw HTML in markdown content
