baseURL = "https://daily.shuang.blog/"
defaultContentLanguage = "zh"  # 默认语言设置为中文
defaultContentLanguageInSubdir = false
# Pagination setting - use this format
paginate = 10  # Shows 10 items per page
# 启用语言
[languages]
  [languages.zh]
    languageName = "中文"
    title = ""
    weight = 1  # 中文优先权重
  [languages.en]
    languageName = "English"
    title = "Daily Thoughts"
    weight = 2
# 主题配置
theme = "paper"
# Paper 主题配置
[params]
  # 颜色主题
  color = "linen"  # linen, wheat, gray, light
  # 头部社交图标
  mastodon = "https://yangyang.how/@shuang"  # 更新为您的用户名
  threads = "https://www.threads.net/@0b00101111"    # 更新为您的用户名
  # 首页个人资料
  avatar = "avatar.jpg"    # 放置在 static/images/ 目录下
  name = "47"
  bio = "Existence precedes essence."
  # 其他设置
  disableHLJS = true       # 禁用 highlight.js
  monoDarkIcon = true      # 显示单色暗模式图标
  # 主要内容区域设置
  mainSections = ["posts", "thoughts", "daily"]
# 永久链接 - 影响 URL 结构
[permalinks]
  posts = "/blog/:year/:month/:title/"
  moments = "/moments/:year/:month/:title/"
  daily = "/daily/:year/:month/:day/"
# 分类设置
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# 中文菜单配置
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "博客"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "moments"
    name = "瞬间"
    url = "/moments/"
    weight = 20
  [[menu.main]]
    identifier = "daily"
    name = "日常"
    url = "/zh/daily/"
    weight = 30
  [[menu.main]]
    identifier = "language"
    name = "中文 / EN"
    url = "#"
    weight = 40

# 英文菜单配置
[languages.en.menu]
  [[languages.en.menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/en/posts/"
    weight = 10
  [[languages.en.menu.main]]
    identifier = "moments"
    name = "moments"
    url = "/en/moments/"
    weight = 20
  [[languages.en.menu.main]]
    identifier = "daily"
    name = "Daily Digest"
    url = "/en/daily/"
    weight = 30
  [[languages.en.menu.main]]
    identifier = "language"
    name = "中文 / EN"
    url = "#"
    weight = 40

# 英文参数
[languages.en.params]
  bio = "Capturing thoughts as they happen"
